version: '3.8'

services:
  debug-alice-ai-mysql:
    image: mysql:latest
    container_name: debug-alice-ai-mysql
    privileged: true
    ports:
      - 3306:3306
    volumes:
      - mysql-data:/var/lib/alice-mysql
    healthcheck:
      test: [ "CMD-SHELL", "mysqladmin ping -h localhost -u$$MYSQL_USER -p$$MYSQL_PASSWORD" ]
      interval: 5s
      retries: 10
    env_file:
      - ../../envs/local/mysql.env
volumes:
  mysql-data:
    name: mysql-data
    external: true

# docker-compose -f docker/local/docker-compose.yml up -d --no-build